# Generated by Django 3.1.2 on 2020-10-23 22:10

import analyst.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('kind', models.CharField(choices=[('I', 'Indice'), ('S', 'Stock'), ('F', 'Forex'), ('C', 'Crypto-currency')], max_length=1, null=True)),
                ('ticker', models.CharField(max_length=30, null=True)),
                ('country', models.CharField(max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('init_source', models.CharField(max_length=32)),
                ('data_source', models.CharField(max_length=32)),
                ('extra_data', models.JSONField(default=dict, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
            bases=(models.Model, analyst.models.UpdateMixin),
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('indices', models.JSONField(default=dict, null=True)),
                ('weights', models.JSONField(default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assets', models.ManyToManyField(to='analyst.Asset')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('country', models.CharField(max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('init_source', models.CharField(max_length=32)),
                ('asset', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='indice', to='analyst.asset')),
                ('components', models.ManyToManyField(to='analyst.Asset')),
            ],
            options={
                'ordering': ['id'],
            },
            bases=(models.Model, analyst.models.UpdateMixin),
        ),
    ]
